# Generated by Django 2.2.6 on 2019-10-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='he',
        ),
        migrations.DeleteModel(
            name='P',
        ),
    ]
