# Generated by Django 2.2.6 on 2019-10-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('Email', models.CharField(blank=True, max_length=200, null=True)),
                ('birth', models.CharField(blank=True, max_length=200, null=True)),
                ('个性签名', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_image', models.FileField(upload_to='profile_image')),
                ('实名', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
