# Generated by Django 2.2.6 on 2019-10-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_auto_20191024_2247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People',
        ),
    ]
