# Generated by Django 2.2.6 on 2019-10-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_person_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='status',
        ),
    ]
