# Generated by Django 2.2.6 on 2019-10-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_remove_person_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
