# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-14 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200413_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user_profile_id',
            new_name='user_profile',
        ),
        migrations.AlterField(
            model_name='address',
            name='receiver',
            field=models.CharField(max_length=11, verbose_name='收件人名'),
        ),
    ]
